[root][12:40:39 PM][INFO]: Server startup initialized
[root][12:40:39 PM][INFO]: Opening server at "localhost" with the port 19391
[root][12:40:39 PM][INFO]: Server is online
[websockets.server][12:40:44 PM][INFO]: connection open
[websockets.server][12:40:44 PM][INFO]: A Client with the IP ('127.0.0.1', 19391) has connected
[websockets.server][12:40:44 PM][INFO]: ('127.0.0.1', 19391) has now been registered with id: 2594c1a7-d456-417d-b458-c98f8a5baab5
[websockets.server][12:40:44 PM][INFO]: ('127.0.0.1', 19391) has connected with correct response
[websockets.server][12:40:44 PM][WARNING]: Warning
[websockets.server][12:40:44 PM][ERROR]: connection handler failed
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/websockets/sync/server.py", line 498, in conn_handler
    handler(connection)
  File "/Users/marklopezjr./Desktop/Python projects/Websocket Computer Management System/Server/server.py", line 36, in handler
    username = json.loads(websocket.recv())
                          ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/websockets/sync/connection.py", line 198, in recv
    raise self.protocol.close_exc from self.recv_events_exc
websockets.exceptions.ConnectionClosedOK: received 1000 (OK) Failed to handshake with server; then sent 1000 (OK) Failed to handshake with server
